[project]
name = "lab9-spatial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.2",
    "geopandas>=1.1.1",
    "ibis-framework[duckdb,polars]>=11.0.0",
    "lonboard>=0.13.0",
    "polars>=1.35.2",
]
